### ISSUE TITLE
How about this?

### ISSUE THREAD

**Issue by Zibri** [cyrozap/python-vipaccess#11]
When you use vip access, you tell the bank the vip access id (VSSxxxxx) so they can have your keys to authenticate you. How can we do the same?
A utility like yours that query Symantec server with a vip access I'd and returns the data needed for authenticating that ID. ..

**Comment by cyrozap** [comment]
Closing this issue since I'm no longer maintaining this project and will be archiving it soon. Please use [this fork](https://github.com/dlenski/python-vipaccess) instead.
