### ISSUE TITLE
vipaccess errors with "Something went wrong--the token is invalid."

### ISSUE THREAD

**Issue by simnim** [cyrozap/python-vipaccess#13]
Hi there,
I'm eager to be able to use your script, but after I installed python-vipaccess from pip and ran the program I got the following cryptic error:
"Something went wrong--the token is invalid."

Any idea how it can be fixed?

**Comment by SamEvansTurner** [comment]
I am also having this issue. Would be nice to get it working.

**Comment by zecoj** [comment]
I made a pull request to fix this issue, just waiting on cyrozap. Meanwhile, you can try this: https://github.com/zecoj/python-vipaccess

**Comment by simnim** [comment]
Totally works. Thanks!

**Comment by Alizoo** [comment]
Hi, having the same issue of 'the token is invalid', even with zecoj's newer version. Any chance of updating this to get it working again? Or is the error at my end?

**Comment by aitte2** [comment]
Just go to this fork: https://github.com/dlenski/python-vipaccess

It contains @zecoj's fix for the new symantec token-check URL, and tons of other bugfixes. Use that instead of this @cyrozap unmaintained original (no updates since 2015). Thanks to cyrozap though, for your hard original work! :-)

**Comment by cyrozap** [comment]
Closing this issue since I'm no longer maintaining this project and will be archiving it soon. Please use [this fork](https://github.com/dlenski/python-vipaccess) instead.
