### ISSUE TITLE
Invalid Tokens

### ISSUE THREAD

**Issue by skonagaya** [cyrozap/python-vipaccess#16]
Code generated by the python app seems to be invalid. Anyone else having issues?

I'm using this URL to verify:  https://idprotect.vip.symantec.com/otpCheck

Also, when I try the command `vipaccess provision`. I get _Something went wrong--the token is invalid._ 

Could the OTP be invalid?

**Comment by cyrozap** [comment]
Closing this issue since I'm no longer maintaining this project and will be archiving it soon. Please use [this fork](https://github.com/dlenski/python-vipaccess) instead.
