### ISSUE TITLE
fedora 27 and ubuntu 17.1 issue

### ISSUE THREAD

**Issue by gianmuc** [cyrozap/python-vipaccess#17]
Hi, I installed everything but when I try to star vipaccess from terminal it gives me error 
- Something went wrong--the token is invalid.-
I already tried stuff written in others comments but nothing to do. What could be the problem_

**Comment by p07r0457** [comment]
Also fails on Mac OS X 10.13.2 using Python 3.6.4.

**Comment by p07r0457** [comment]
@gianmuc Check pull request #14.  I applied that and it's now working for me.

**Comment by cyrozap** [comment]
Closing this issue since I'm no longer maintaining this project and will be archiving it soon. Please use [this fork](https://github.com/dlenski/python-vipaccess) instead.
