### ISSUE TITLE
Install instructions incorrect, doesn't work anyway

### ISSUE THREAD

**Issue by TotallyInformation** [cyrozap/python-vipaccess#20]
This version of this tool doesn't work as far as I can tell.

Firstly, I could only install at all using the Python3 version of pip. Then the executable isn't on the path unless you install with sudo. Then running it gives `Something went wrong--the token is invalid.`.

This version appears to be unmaintained.

I will try this version:

https://github.com/dlenski/python-vipaccess

I have documented the whole process end-to-end on my blog. That post also contains the history and gives a way of using an app that doesn't require any of the messing around that this application does.

https://it.knightnet.org.uk/blog/use-an-authenticator-app-to-login-to-paypal/

**Comment by cyrozap** [comment]
Closing this issue since I'm no longer maintaining this project and will be archiving it soon. Please use [this fork](https://github.com/dlenski/python-vipaccess) instead.
