### ISSUE TITLE
Emulate Mobile VIP app

### ISSUE THREAD

**Issue by mew1033** [cyrozap/python-vipaccess#8]
In your blog post, you mentioned you might one day add the capability to emulate the mobile version of VIP Access. Any chance you've looked into that at all?

**Comment by vr** [comment]
:+1: because Desktop version is banned sometimes

**Comment by mew1033** [comment]
https://github.com/dlenski/python-vipaccess

**Comment by dlenski** [comment]
If you don't want to use my fork (which lacks built-in QR code support), then the patch to switch to the "mobile" token type is truly trivial: https://github.com/dlenski/python-vipaccess/commit/912166e2c1626b6f16d9783434bf8d577bd7039d

**Comment by cyrozap** [comment]
Closing this issue since I'm no longer maintaining this project and will be archiving it soon. Please use [this fork](https://github.com/dlenski/python-vipaccess) instead.
